# Generated by Django 4.2.23 on 2025-07-07 17:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adminpanel', '0006_makeuptype_description_alter_makeuptype_name'),
        ('artists', '0012_remove_artistprofile_certifications_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(blank=True, max_length=255, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=15, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('event_type', models.CharField(choices=[('wedding', 'Wedding'), ('engagement', 'Engagement'), ('party', 'Party'), ('corporate', 'Corporate'), ('other', 'Other')], max_length=20)),
                ('requirements', models.TextField(blank=True)),
                ('booking_date', models.DateField()),
                ('source', models.CharField(blank=True, choices=[('website', 'Website'), ('instagram', 'Instagram'), ('referral', 'Referral'), ('other', 'Other')], max_length=50, null=True)),
                ('status', models.CharField(choices=[('new', 'New'), ('contacted', 'Contacted'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted')], default='new', max_length=20)),
                ('last_contact', models.DateTimeField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_leads', to='artists.artistprofile')),
                ('budget_range', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.budgetrange')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('location', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='artists.location')),
                ('makeup_types', models.ManyToManyField(blank=True, to='adminpanel.makeuptype')),
                ('requested_artist', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_leads', to='artists.artistprofile')),
                ('service', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='adminpanel.service')),
            ],
        ),
    ]
