# Generated by Django 4.2.23 on 2025-07-12 18:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('documents', '0004_document_file_url_document_is_active_and_more'),
        ('artists', '0012_remove_artistprofile_certifications_and_more'),
        ('leads', '0004_leaddistributionconfig_leaddistributionrule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FalseLeadClaim',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.TextField()),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('admin_note', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='false_lead_claims', to='artists.artistprofile')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='false_claims', to='leads.lead')),
                ('proof_document', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.document')),
                ('resolved_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_false_claims', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
