# Generated by Django 4.2.23 on 2025-07-12 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_file_url_document_is_active_and_more'),
        ('leads', '0005_falseleadclaim'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falseleadclaim',
            name='resolved_by',
        ),
        migrations.AddField(
            model_name='falseleadclaim',
            name='proof_documents',
            field=models.ManyToManyField(blank=True, related_name='false_lead_claims', to='documents.document'),
        ),
    ]
