# Generated by Django 4.2.23 on 2025-07-12 18:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('leads', '0006_remove_falseleadclaim_resolved_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falseleadclaim',
            name='proof_document',
        ),
        migrations.AddField(
            model_name='falseleadclaim',
            name='resolved_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resolved_false_claims', to=settings.AUTH_USER_MODEL),
        ),
    ]
