# Generated by Django 4.2.23 on 2025-07-12 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0007_remove_falseleadclaim_proof_document_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='falseleadclaim',
            old_name='proof_documents',
            new_name='proof_document',
        ),
    ]
