# Generated by Django 4.2.23 on 2025-07-12 18:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0008_rename_proof_documents_falseleadclaim_proof_document'),
    ]

    operations = [
        migrations.RenameField(
            model_name='falseleadclaim',
            old_name='proof_document',
            new_name='proof_documents',
        ),
    ]
