# Generated by Django 4.2.23 on 2025-08-31 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0028_artistprofile_my_claimed_leads'),
        ('leads', '0010_alter_lead_status_selectedartist'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='booked_artists',
            field=models.ManyToManyField(blank=True, related_name='booked_leads', to='artists.artistprofile'),
        ),
        migrations.AddField(
            model_name='lead',
            name='claimed_artists',
            field=models.ManyToManyField(blank=True, related_name='claimed_leads', to='artists.artistprofile'),
        ),
        migrations.AddField(
            model_name='lead',
            name='max_claims',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AlterField(
            model_name='lead',
            name='status',
            field=models.CharField(choices=[('new', 'New'), ('claimed', 'Claimed'), ('booked', 'Booked'), ('qualified', 'Qualified'), ('unqualified', 'Unqualified'), ('converted', 'Converted')], default='new', max_length=20),
        ),
    ]
