# Generated by Django 4.2.23 on 2025-08-31 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0011_lead_booked_artists_lead_claimed_artists_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
