# Generated by Django 4.2.23 on 2025-08-31 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0012_lead_total_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='total_claims',
            field=models.IntegerField(default=0),
        ),
    ]
