# Generated by Django 4.2.23 on 2025-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0014_fix_total_bookings_default'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='location',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
