# Generated by Django 4.2.23 on 2025-09-08 18:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0015_alter_lead_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='FalseClaimDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=255)),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('doc', 'DOC'), ('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('dl', 'Driving License'), ('other', 'Other')], default='image', max_length=10)),
                ('file_url', models.URLField(blank=True, max_length=1000, null=True)),
                ('public_id', models.CharField(blank=True, max_length=255, null=True)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('false_claim', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='leads.falseleadclaim')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='false_claim_documents', to='leads.lead')),
            ],
        ),
    ]
