# Generated by Django 4.2.23 on 2025-09-14 12:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0016_falseclaimdocument'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='falseleadclaim',
            name='proof_documents',
        ),
    ]
