# Generated by Django 4.2.23 on 2025-09-20 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0017_remove_falseleadclaim_proof_documents'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lead',
            name='event_type',
            field=models.CharField(blank=True, choices=[('wedding', 'Wedding'), ('engagement', 'Engagement'), ('party', 'Party'), ('corporate', 'Corporate'), ('other', 'Other')], max_length=20, null=True),
        ),
    ]
