# Generated by Django 4.2.23 on 2025-10-11 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0018_alter_lead_event_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='is_verified',
            field=models.BooleanField(default=True),
        ),
    ]
