# Generated by Django 4.2.23 on 2025-11-05 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0019_lead_is_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lead',
            name='budget_range',
        ),
        migrations.AddField(
            model_name='lead',
            name='budget',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
