# Generated by Django 4.2.23 on 2025-08-21 10:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0023_artistprofile_available_leads'),
        ('adminpanel', '0014_service_credits'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistCreditBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lead_credits', models.IntegerField(default=0)),
                ('premium_feature_credits', models.IntegerField(default=0)),
                ('boost_profile_credits', models.IntegerField(default=0)),
                ('total_lead_credits_earned', models.IntegerField(default=0)),
                ('total_premium_credits_earned', models.IntegerField(default=0)),
                ('total_boost_credits_earned', models.IntegerField(default=0)),
                ('total_lead_credits_consumed', models.IntegerField(default=0)),
                ('total_premium_credits_consumed', models.IntegerField(default=0)),
                ('total_boost_credits_consumed', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='credit_balance', to='artists.artistprofile')),
            ],
            options={
                'verbose_name': 'Artist Credit Balance',
                'verbose_name_plural': 'Artist Credit Balances',
            },
        ),
        migrations.CreateModel(
            name='CreditTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_type', models.CharField(choices=[('purchase', 'Purchase'), ('consumption', 'Consumption'), ('refund', 'Refund'), ('adjustment', 'Adjustment')], max_length=20)),
                ('credit_type', models.CharField(choices=[('lead_credit', 'Lead Credit'), ('premium_feature', 'Premium Feature'), ('boost_profile', 'Boost Profile')], default='lead_credit', max_length=20)),
                ('credits_before', models.IntegerField(default=0)),
                ('credits_amount', models.IntegerField()),
                ('credits_after', models.IntegerField(default=0)),
                ('description', models.TextField(blank=True)),
                ('reference_id', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='credit_transactions', to='artists.artistprofile')),
                ('subscription_plan', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='credit_transactions', to='adminpanel.subscriptionplan')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['artist', 'created_at'], name='credit_hist_artist__ff0345_idx'), models.Index(fields=['transaction_type', 'credit_type'], name='credit_hist_transac_6137b3_idx'), models.Index(fields=['artist', 'transaction_type'], name='credit_hist_artist__99cd19_idx')],
            },
        ),
    ]
