# Generated by Django 4.2.23 on 2025-08-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credit_history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='credittransaction',
            name='credit_type',
            field=models.CharField(choices=[('lead_credit', 'Lead Credit'), ('premium_feature', 'Premium Feature'), ('boost_profile', 'Boost Profile'), ('referral', 'Referral')], default='lead_credit', max_length=20),
        ),
        migrations.AlterField(
            model_name='credittransaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('consumption', 'Consumption'), ('refund', 'Refund'), ('adjustment', 'Adjustment'), ('referral', 'Referral')], max_length=20),
        ),
    ]
