# Generated by Django 4.2.23 on 2025-06-28 19:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
    ]
