# Generated by Django 4.2.23 on 2025-06-29 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_auto_20250629_0051'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='subscriptionplanfeature',
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name='subscriptionplanfeature',
            name='feature',
        ),
        migrations.RemoveField(
            model_name='subscriptionplanfeature',
            name='subscription_plan',
        ),
        migrations.AddField(
            model_name='subscriptionplan',
            name='features',
            field=models.JSONField(default=list, help_text='List of feature names selected for this plan'),
        ),
        migrations.DeleteModel(
            name='Feature',
        ),
        migrations.DeleteModel(
            name='SubscriptionPlanFeature',
        ),
    ]
