# Generated by Django 4.2.23 on 2025-07-07 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0004_budgetrange_makeuptype_service'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='makeuptype',
            name='description',
        ),
        migrations.AlterField(
            model_name='makeuptype',
            name='name',
            field=models.CharField(max_length=100),
        ),
    ]
