# Generated by Django 4.2.23 on 2025-07-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0005_remove_makeuptype_description_alter_makeuptype_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='makeuptype',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='makeuptype',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
