# Generated by Django 4.2.23 on 2025-08-16 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0013_service_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='credits',
            field=models.IntegerField(default=0),
        ),
    ]
