# Generated by Django 4.2.23 on 2025-08-24 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0014_service_credits'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='total_credit_leads',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
