# Generated by Django 4.2.23 on 2025-08-24 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0015_subscriptionplan_total_credit_leads'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subscriptionplan',
            old_name='total_credit_leads',
            new_name='total_credit_points',
        ),
    ]
