# Generated by Django 4.2.23 on 2025-10-17 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_rename_total_credit_leads_subscriptionplan_total_credit_points'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionplan',
            name='claim_amount_limit',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Maximum amount limit for lead claims', max_digits=10, null=True),
        ),
    ]
