# Generated by Django 4.2.23 on 2025-08-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogs', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='project_id',
            field=models.IntegerField(unique=True),
        ),
    ]
