# Generated by Django 3.2 on 2025-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_path', models.FileField(upload_to='documents/')),
                ('file_type', models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('doc', 'DOC'), ('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('dl', 'Driving License'), ('other', 'Other'), ('other', 'Other')], default='image', max_length=10)),
                ('tag', models.CharField(blank=True, max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
