# Generated by Django 3.2 on 2025-06-25 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_uploaded_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='file_path',
        ),
        migrations.AddField(
            model_name='document',
            name='file_data',
            field=models.BinaryField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='file_name',
            field=models.CharField(default='default_name', max_length=255),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_type',
            field=models.CharField(choices=[('image', 'Image'), ('pdf', 'PDF'), ('doc', 'DOC'), ('aadhar', 'Aadhar Card'), ('pan', 'PAN Card'), ('dl', 'Driving License'), ('other', 'Other')], default='image', max_length=10),
        ),
    ]
