# Generated by Django 4.2.23 on 2025-06-26 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_auto_20250626_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='file_url',
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='document',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='document',
            name='public_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
