"""
Django settings for wedmac_services project.

Generated by 'django-admin startproject' using Django 4.2.23.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from datetime import timedelta
from pathlib import Path
import cloudinary #type : ignore


# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-9-s0ao(gd)ml=cvbo3-bbw@1)^$i3w0c5iql@%7h=_2c6k&cla'

# SECURITY WARNING: don't run with debug turned on in production!
import os

DEBUG = True
# DEBUG = os.getenv("DEBUG", "False") == "True"

ALLOWED_HOSTS = ["89.116.33.217 ", "localhost", "127.0.0.1","wedmac-be.onrender.com","api.wedmacindia.com"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
     'rest_framework',
    'rest_framework_simplejwt',
    'corsheaders',
    # Custom apps
    'cloudinary',
    'artists',
    'users',
    'subscriptions',
    'leads',
    'grievances',
    'adminpanel',
    'notifications',  
    'cms',            
    'documents',  
    'appconfig',
    'media',
    'ratings',
    'public', 
    "blogs",
    'superadmin_auth',
    'credit_history',
    "support_help",
    'artist_services',
    'content_management',
]

AUTH_USER_MODEL = 'users.User'
REST_FRAMEWORK = {
    'DEFAULT_AUTHENTICATION_CLASSES': (
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    )
}
CORS_ALLOWED_ORIGINS = [
    "http://localhost:3000","https://wedmac-be.onrender.com", "https://wedmacindia.com",
]
CORS_ALLOW_ALL_ORIGINS = True
CSRF_TRUSTED_ORIGINS = [
    "https://wedmac-services.onrender.com","https://wedmac-be.onrender.com","https://wedmacindia.com",
    # Add other domains if needed
]
MIDDLEWARE = [
        'corsheaders.middleware.CorsMiddleware',  # 👈 Must be near the top
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'wedmac_services.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'wedmac_services.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases


# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'wedmac',
#         'USER': 'wedmac',
#         'PASSWORD': 'wedmac_psw',
#         'HOST': 'localhost',
#         'PORT': '3306',
#     }
# }

# DATABASES = {
#     'default': {
#         'ENGINE': 'django.db.backends.mysql',
#         'NAME': 'wedmac',
#         'USER': 'root',
#         'PASSWORD': 'KsxFeBvKPbHpBbeJHDlOHbMZJQrvLKTJ',
#         'HOST': 'switchyard.proxy.rlwy.net',
#         'PORT': '20897',
#     }
# }
#new live railway db
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'wedmac',
        'USER': 'root',
        'PASSWORD': 'CBVtBgYaNvTyZsyolMSGmGwEkDldZfbm',
        'HOST': 'switchyard.proxy.rlwy.net',
        'PORT': '39675',
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

TWOFACTOR_API_KEY = "481b9b49-4f9e-11f0-a562-0200cd936042" # Replace with your actual API key
DLT_TAG = "WEDMAC"  # Replace with your actual DLT tag
# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = 'static/'

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'


SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(minutes=6000),  # 🔁 Change this to your desired duration
    'REFRESH_TOKEN_LIFETIME': timedelta(days=70),     # Optional: adjust refresh token time too
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': True,

    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,

    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

import os
import cloudinary

cloudinary.config(
    cloud_name=os.getenv("CLOUDINARY_CLOUD_NAME", "dyu12nerp"),
    api_key=os.getenv("CLOUDINARY_API_KEY", "639518621389713"),
    api_secret=os.getenv("CLOUDINARY_API_SECRET", "1nW-c9zM0gUMs8Sp-SCgb9_mDNM")
)

# Default File Storage (for images and media)
DEFAULT_FILE_STORAGE = 'cloudinary_storage.storage.MediaCloudinaryStorage'

# Razorpay Credentials
RAZORPAY_KEY_ID = 'rzp_test_l7Py4KSkXnLSgC'
RAZORPAY_KEY_SECRET = 'I4eHRaAOY8fnVaMH5lCXqMxP'
