# Generated by Django 4.2.23 on 2025-08-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('support_help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ticket',
            name='category',
            field=models.CharField(choices=[('account', 'Account Issues'), ('payment', 'Payment Issues'), ('technical', 'Technical Issues'), ('content', 'Content Related'), ('profile', 'Profile Related'), ('other', 'Other')], max_length=50),
        ),
    ]
