# Generated by Django 4.2.23 on 2025-08-25 18:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(help_text="The client's review description.")),
                ('client_name', models.CharField(help_text='The name of the client.', max_length=100)),
                ('location', models.CharField(blank=True, help_text="The client's location.", max_length=100, null=True)),
                ('used_service', models.CharField(help_text='The name of the service used by the client.', max_length=200)),
                ('rating', models.IntegerField(help_text='Rating out of 5 stars.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Review',
                'verbose_name_plural': 'Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
