# Generated by Django 4.2.23 on 2025-08-25 18:34

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='images',
            field=cloudinary.models.CloudinaryField(blank=True, help_text='An image associated with the review.', max_length=255, null=True, verbose_name='images'),
        ),
    ]
