# Generated by Django 4.2.23 on 2025-08-25 18:56

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content_management', '0002_review_images'),
    ]

    operations = [
        migrations.CreateModel(
            name='VideoReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(help_text="The client's video review comment.")),
                ('client_name', models.CharField(help_text='The name of the client.', max_length=100)),
                ('location', models.CharField(blank=True, help_text="The client's location.", max_length=100, null=True)),
                ('used_service', models.CharField(help_text='The name of the service used by the client.', max_length=200)),
                ('video', cloudinary.models.CloudinaryField(blank=True, help_text='A video associated with the review.', max_length=255, null=True, verbose_name='video')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Video Review',
                'verbose_name_plural': 'Video Reviews',
                'ordering': ['-created_at'],
            },
        ),
    ]
