# Generated by Django 3.2 on 2025-06-22 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('gender', models.CharField(blank=True, max_length=10)),
                ('date_of_birth', models.DateField(blank=True, null=True)),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(default='India', max_length=100)),
                ('referel_code', models.CharField(blank=True, max_length=20)),
                ('offer_chosen', models.CharField(blank=True, max_length=100)),
                ('bio', models.TextField(blank=True)),
                ('type_of_makeup', models.CharField(blank=True, max_length=100)),
                ('price_range', models.CharField(blank=True, max_length=100)),
                ('products_used', models.TextField(blank=True)),
                ('experience_years', models.PositiveIntegerField(default=0)),
                ('services', models.JSONField(blank=True, default=list)),
                ('travel_charges', models.BooleanField(default=False)),
                ('trial_available', models.BooleanField(default=False)),
                ('social_links', models.JSONField(blank=True, default=dict)),
                ('payment_status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid')], default='pending', max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('internal_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
