# Generated by Django 3.2 on 2025-06-22 17:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('documents', '0001_initial'),
        ('artists', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='certifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='certifications', to='documents.document'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='id_documents',
            field=models.ManyToManyField(blank=True, related_name='id_documents', to='documents.Document'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='profile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_picture', to='documents.document'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='supporting_images',
            field=models.ManyToManyField(blank=True, related_name='supporting_images', to='documents.Document'),
        ),
    ]
