# Generated by Django 4.2.23 on 2025-06-22 18:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0003_artistprofile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('pincode', models.CharField(max_length=10)),
                ('lat', models.FloatField()),
                ('lng', models.FloatField()),
            ],
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='city',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='country',
        ),
        migrations.RemoveField(
            model_name='artistprofile',
            name='state',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profiles', to='artists.location'),
        ),
    ]
