# Generated by Django 4.2.23 on 2025-06-26 16:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_file_url_document_is_active_and_more'),
        ('artists', '0004_location_remove_artistprofile_city_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='certifications',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_certification', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='id_documents',
            field=models.ManyToManyField(blank=True, related_name='artist_id_documents', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='profile_picture',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artist_profile_picture', to='documents.document'),
        ),
        migrations.AlterField(
            model_name='artistprofile',
            name='supporting_images',
            field=models.ManyToManyField(blank=True, related_name='artist_supporting_images', to='documents.document'),
        ),
    ]
