# Generated by Django 4.2.23 on 2025-06-26 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0005_alter_artistprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
