# Generated by Django 4.2.23 on 2025-06-28 19:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
        ('artists', '0006_alter_artistprofile_phone'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistSubscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField()),
                ('total_leads_allocated', models.IntegerField()),
                ('leads_used', models.IntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artists.artistprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.subscriptionplan')),
            ],
        ),
    ]
