# Generated by Django 4.2.23 on 2025-06-29 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0007_artistsubscription'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsubscription',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
