# Generated by Django 4.2.23 on 2025-06-29 19:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0008_artistsubscription_payment_status'),
    ]

    operations = [
    ]
