# Generated by Django 4.2.23 on 2025-06-29 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0009_auto_20250630_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistsubscription',
            name='razorpay_order_id',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
