# Generated by Django 4.2.23 on 2025-06-29 20:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0010_artistsubscription_razorpay_order_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsubscription',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='artistsubscription',
            name='total_leads_allocated',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
