# Generated by Django 4.2.23 on 2025-06-30 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0004_document_file_url_document_is_active_and_more'),
        ('artists', '0011_alter_artistsubscription_end_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='certifications',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='certifications',
            field=models.ManyToManyField(blank=True, related_name='artist_certifications', to='documents.document'),
        ),
    ]
