# Generated by Django 4.2.23 on 2025-07-24 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0012_remove_artistprofile_certifications_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='average_rating',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='total_ratings',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
