# Generated by Django 4.2.23 on 2025-07-24 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0006_makeuptype_description_alter_makeuptype_name'),
        ('artists', '0013_artistprofile_average_rating_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='type_of_makeup',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='type_of_makeup',
            field=models.ManyToManyField(blank=True, related_name='artist_profiles', to='adminpanel.makeuptype'),
        ),
    ]
