# Generated by Django 4.2.23 on 2025-07-24 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0007_product_alter_budgetrange_id_alter_makeuptype_id_and_more'),
        ('artists', '0014_remove_artistprofile_type_of_makeup_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='products_used',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='products_used',
            field=models.ManyToManyField(blank=True, related_name='artist_profiles', to='adminpanel.product'),
        ),
    ]
