# Generated by Django 4.2.23 on 2025-07-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0015_remove_artistprofile_products_used_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='id',
            field=models.UUIDField(editable=False, primary_key=True, serialize=False),
        ),
    ]
