# Generated by Django 4.2.23 on 2025-07-24 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0016_alter_artistprofile_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
