# Generated by Django 4.2.23 on 2025-07-25 19:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0010_paymentmethod'),
        ('artists', '0017_alter_artistprofile_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='social_links',
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='payment_methods',
            field=models.ManyToManyField(blank=True, related_name='artist_profiles', to='adminpanel.paymentmethod'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='travel_policy',
            field=models.TextField(blank=True),
        ),
        migrations.CreateModel(
            name='SocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('platform', models.CharField(max_length=50)),
                ('url', models.URLField()),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='social_links', to='artists.artistprofile')),
            ],
        ),
    ]
