# Generated by Django 4.2.23 on 2025-07-25 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0018_remove_artistprofile_social_links_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='travel_charges',
            field=models.TextField(default=False),
        ),
    ]
