# Generated by Django 4.2.23 on 2025-08-02 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0019_alter_artistprofile_travel_charges'),
    ]

    operations = [
        migrations.AlterField(
            model_name='location',
            name='lat',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='lng',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='location',
            name='pincode',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
