# Generated by Django 4.2.23 on 2025-08-15 17:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0020_alter_location_lat_alter_location_lng_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='sociallink',
            unique_together={('artist', 'platform')},
        ),
    ]
