# Generated by Django 4.2.23 on 2025-08-17 18:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0021_alter_sociallink_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='trial_paid_type',
            field=models.CharField(blank=True, choices=[('paid', 'Paid'), ('unpaid', 'Unpaid')], max_length=10, null=True),
        ),
    ]
