# Generated by Django 4.2.23 on 2025-08-23 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0023_artistprofile_available_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='my_referral_code',
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
