# Generated by Django 4.2.23 on 2025-08-30 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0024_artistprofile_my_referral_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsubscription',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed'), ('canceled', 'Canceled')], default='pending', max_length=20),
        ),
    ]
