# Generated by Django 4.2.23 on 2025-08-30 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0025_alter_artistsubscription_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistsubscription',
            name='payment_status',
            field=models.CharField(choices=[('pending', 'Pending'), ('success', 'Success'), ('failed', 'Failed')], default='pending', max_length=20),
        ),
    ]
