# Generated by Django 4.2.23 on 2025-08-30 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0026_alter_artistsubscription_payment_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
