# Generated by Django 4.2.23 on 2025-08-30 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0027_artistprofile_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='my_claimed_leads',
            field=models.IntegerField(default=0),
        ),
    ]
