# Generated by Django 4.2.23 on 2025-09-01 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0028_artistprofile_my_claimed_leads'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='total_bookings',
            field=models.IntegerField(default=0),
        ),
    ]
