# Generated by Django 4.2.23 on 2025-09-06 09:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0029_artistprofile_total_bookings'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='tag',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
