# Generated by Django 4.2.23 on 2025-09-07 09:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_rename_total_credit_leads_subscriptionplan_total_credit_points'),
        ('artists', '0030_artistprofile_tag'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='created_by_admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='current_purchase_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='artists_with_current_plan', to='adminpanel.subscriptionplan'),
        ),
    ]
