# Generated by Django 4.2.23 on 2025-09-07 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0031_artistprofile_created_by_admin_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='artistprofile',
            name='current_purchase_plan',
        ),
    ]
