# Generated by Django 4.2.23 on 2025-09-07 11:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_rename_total_credit_leads_subscriptionplan_total_credit_points'),
        ('artists', '0032_remove_artistprofile_current_purchase_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='current_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='current_artist_profiles', to='adminpanel.subscriptionplan'),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='plan_purchase_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artistprofile',
            name='plan_verified',
            field=models.BooleanField(default=False),
        ),
    ]
