# Generated by Django 4.2.23 on 2025-09-14 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0033_artistprofile_current_plan_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='extended_days',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
