# Generated by Django 4.2.23 on 2025-09-20 05:03

from django.db import migrations, models


def convert_tag_to_array(apps, schema_editor):
    """Convert existing string tags to arrays"""
    ArtistProfile = apps.get_model('artists', 'ArtistProfile')

    for artist in ArtistProfile.objects.all():
        if artist.tag and isinstance(artist.tag, str):
            # Convert string to array, handling empty strings
            if artist.tag.strip():
                artist.tag = [artist.tag.strip()]
            else:
                artist.tag = []
            artist.save()


def convert_array_to_string(apps, schema_editor):
    """Reverse migration: convert arrays back to strings"""
    ArtistProfile = apps.get_model('artists', 'ArtistProfile')

    for artist in ArtistProfile.objects.all():
        if artist.tag and isinstance(artist.tag, list):
            # Convert first tag to string, or empty string if no tags
            artist.tag = artist.tag[0] if artist.tag else ''
            artist.save()


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0034_artistprofile_extended_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artistprofile',
            name='tag',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
        migrations.RunPython(convert_tag_to_array, convert_array_to_string),
    ]
