# Generated by Django 4.2.23 on 2025-09-25 18:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0016_rename_total_credit_leads_subscriptionplan_total_credit_points'),
        ('artists', '0037_add_artistprofile_date_of_birth'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExpiredPlanLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_purchase_date', models.DateTimeField()),
                ('plan_expiry_date', models.DateTimeField()),
                ('available_leads_before_expiry', models.IntegerField()),
                ('expired_at', models.DateTimeField(auto_now_add=True)),
                ('plan_details', models.JSONField(help_text='Snapshot of plan details at expiry time')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='expired_plan_logs', to='artists.artistprofile')),
                ('plan', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminpanel.subscriptionplan')),
            ],
            options={
                'verbose_name': 'Expired Plan Log',
                'verbose_name_plural': 'Expired Plan Logs',
                'ordering': ['-expired_at'],
            },
        ),
    ]
