# Generated by Django 4.2.23 on 2025-10-04 14:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0038_expiredplanlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='ArtistActivityLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_type', models.CharField(choices=[('purchase', 'Plan Purchase'), ('claim', 'Lead Claim'), ('expiry', 'Plan Expiry')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('leads_before', models.IntegerField()),
                ('leads_after', models.IntegerField()),
                ('details', models.JSONField(help_text='Additional details like plan info, lead id, etc.')),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_logs', to='artists.artistprofile')),
            ],
            options={
                'verbose_name': 'Artist Activity Log',
                'verbose_name_plural': 'Artist Activity Logs',
                'ordering': ['-timestamp'],
            },
        ),
    ]
