# Generated by Django 4.2.23 on 2025-10-04 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0039_artistactivitylog'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='preferred_locations',
            field=models.JSONField(blank=True, default=list, help_text='List of preferred city names'),
        ),
    ]
