# Generated by Django 4.2.23 on 2025-10-07 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artists', '0040_artistprofile_preferred_locations'),
    ]

    operations = [
        migrations.AddField(
            model_name='artistprofile',
            name='retained_plan_date',
            field=models.DateTimeField(blank=True, help_text='Date when expired plan was retained/reactivated', null=True),
        ),
    ]
