# Generated by Django 4.2.23 on 2025-08-30 13:24

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('artists', '0026_alter_artistsubscription_payment_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='CommentAndRating',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(max_length=20)),
                ('location', models.CharField(max_length=100)),
                ('comment', models.TextField()),
                ('rating', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('artist', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments_and_ratings', to='artists.artistprofile')),
            ],
            options={
                'verbose_name_plural': 'Comments and Ratings',
                'ordering': ['-created_at'],
            },
        ),
    ]
